// Stadium database with travel info from Chatsworth, CA (34.2572, -118.6006)
// Distances are approximate miles, times include 2h airport buffer

const STADIUMS = {
  // SEC STADIUMS
  'alabama': { name: 'Bryant-Denny Stadium', city: 'Tuscaloosa, AL', lat: 33.2084, lng: -87.5503, distance: 1850, airport: 'BHM', toStadium: '1h from BHM', flight: '4h (1 stop)', totalTime: '7.5h', cost: 1000 },
  'arkansas': { name: 'Razorback Stadium', city: 'Fayetteville, AR', lat: 36.0680, lng: -94.1795, distance: 1500, airport: 'XNA', toStadium: '30 min from XNA', flight: '4h (1 stop)', totalTime: '7h', cost: 920 },
  'auburn': { name: 'Jordan-Hare Stadium', city: 'Auburn, AL', lat: 32.6020, lng: -85.4900, distance: 2080, airport: 'ATL', toStadium: '1.5h from ATL', flight: '4h', totalTime: '8h', cost: 1050 },
  'florida': { name: 'Ben Hill Griffin Stadium', city: 'Gainesville, FL', lat: 29.6500, lng: -82.3486, distance: 2350, airport: 'GNV', toStadium: '15 min from GNV', flight: '5h (1 stop)', totalTime: '8h', cost: 1100 },
  'georgia': { name: 'Sanford Stadium', city: 'Athens, GA', lat: 33.9500, lng: -83.3733, distance: 2100, airport: 'ATL', toStadium: '1.5h from ATL', flight: '4h', totalTime: '8h', cost: 1050 },
  'kentucky': { name: 'Kroger Field', city: 'Lexington, KY', lat: 38.0224, lng: -84.5053, distance: 2000, airport: 'LEX', toStadium: '15 min from LEX', flight: '4.5h (1 stop)', totalTime: '7.5h', cost: 1000 },
  'lsu': { name: 'Tiger Stadium', city: 'Baton Rouge, LA', lat: 30.4121, lng: -91.1837, distance: 1800, airport: 'BTR', toStadium: '15 min from BTR', flight: '3.5h', totalTime: '6.5h', cost: 950 },
  'mississippi-state': { name: 'Davis Wade Stadium', city: 'Starkville, MS', lat: 33.4557, lng: -88.7934, distance: 1750, airport: 'GTR', toStadium: '20 min from GTR', flight: '5h (1 stop)', totalTime: '8h', cost: 1050 },
  'missouri': { name: 'Faurot Field', city: 'Columbia, MO', lat: 38.9357, lng: -92.3332, distance: 1600, airport: 'STL', toStadium: '1.5h from STL', flight: '3.5h', totalTime: '7.5h', cost: 900 },
  'oklahoma': { name: 'Gaylord Family Stadium', city: 'Norman, OK', lat: 35.2058, lng: -97.4425, distance: 1340, airport: 'OKC', toStadium: '30 min from OKC', flight: '3h', totalTime: '6h', cost: 850 },
  'ole-miss': { name: 'Vaught-Hemingway Stadium', city: 'Oxford, MS', lat: 34.3617, lng: -89.5345, distance: 1820, airport: 'MEM', toStadium: '1h 20m from MEM', flight: '4h (1 stop)', totalTime: '8h', cost: 980 },
  'south-carolina': { name: 'Williams-Brice Stadium', city: 'Columbia, SC', lat: 33.9727, lng: -81.0194, distance: 2300, airport: 'CAE', toStadium: '15 min from CAE', flight: '5h (1 stop)', totalTime: '8h', cost: 1100 },
  'tennessee': { name: 'Neyland Stadium', city: 'Knoxville, TN', lat: 35.9550, lng: -83.9250, distance: 2060, airport: 'TYS', toStadium: '20 min from TYS', flight: '4.5h (1 stop)', totalTime: '7.5h', cost: 1050 },
  'texas': { name: 'DKR Memorial Stadium', city: 'Austin, TX', lat: 30.2849, lng: -97.7341, distance: 1400, airport: 'AUS', toStadium: '20 min from AUS', flight: '3h', totalTime: '6h', cost: 850 },
  'texas-am': { name: 'Kyle Field', city: 'College Station, TX', lat: 30.6100, lng: -96.3400, distance: 1500, airport: 'CLL', toStadium: '15 min from CLL', flight: '3.5h (1 stop)', totalTime: '6.5h', cost: 900 },
  'vanderbilt': { name: 'FirstBank Stadium', city: 'Nashville, TN', lat: 36.1439, lng: -86.8090, distance: 1850, airport: 'BNA', toStadium: '15 min from BNA', flight: '4h', totalTime: '6.5h', cost: 950 },

  // BIG TEN STADIUMS  
  'illinois': { name: 'Memorial Stadium', city: 'Champaign, IL', lat: 40.0992, lng: -88.2360, distance: 1800, airport: 'CMI', toStadium: '15 min from CMI', flight: '4h (1 stop)', totalTime: '7h', cost: 950 },
  'indiana': { name: 'Memorial Stadium', city: 'Bloomington, IN', lat: 39.1803, lng: -86.5264, distance: 1900, airport: 'IND', toStadium: '1h from IND', flight: '4h', totalTime: '7.5h', cost: 950 },
  'iowa': { name: 'Kinnick Stadium', city: 'Iowa City, IA', lat: 41.6589, lng: -91.5508, distance: 1700, airport: 'CID', toStadium: '15 min from CID', flight: '4h (1 stop)', totalTime: '7h', cost: 920 },
  'maryland': { name: 'SECU Stadium', city: 'College Park, MD', lat: 38.9910, lng: -76.9485, distance: 2420, airport: 'DCA', toStadium: '30 min from DCA', flight: '5h', totalTime: '8h', cost: 1100 },
  'michigan': { name: 'Michigan Stadium', city: 'Ann Arbor, MI', lat: 42.2658, lng: -83.7486, distance: 2100, airport: 'DTW', toStadium: '30 min from DTW', flight: '4.5h', totalTime: '7.5h', cost: 1000 },
  'michigan-state': { name: 'Spartan Stadium', city: 'East Lansing, MI', lat: 42.7284, lng: -84.4833, distance: 2050, airport: 'LAN', toStadium: '15 min from LAN', flight: '4.5h (1 stop)', totalTime: '7.5h', cost: 1000 },
  'minnesota': { name: 'Huntington Bank Stadium', city: 'Minneapolis, MN', lat: 44.9763, lng: -93.2246, distance: 1740, airport: 'MSP', toStadium: '20 min from MSP', flight: '3.5h', totalTime: '6.5h', cost: 950 },
  'nebraska': { name: 'Memorial Stadium', city: 'Lincoln, NE', lat: 40.8206, lng: -96.7056, distance: 1500, airport: 'LNK', toStadium: '15 min from LNK', flight: '4h (1 stop)', totalTime: '7h', cost: 920 },
  'northwestern': { name: 'Ryan Field', city: 'Evanston, IL', lat: 42.0659, lng: -87.6909, distance: 1900, airport: 'ORD', toStadium: '30 min from ORD', flight: '4h', totalTime: '7h', cost: 950 },
  'ohio-state': { name: 'Ohio Stadium', city: 'Columbus, OH', lat: 40.0017, lng: -83.0197, distance: 2100, airport: 'CMH', toStadium: '15 min from CMH', flight: '4.5h', totalTime: '7.5h', cost: 1000 },
  'oregon': { name: 'Autzen Stadium', city: 'Eugene, OR', lat: 44.0584, lng: -123.0681, distance: 820, airport: 'EUG', toStadium: '15 min from EUG', flight: '2h', totalTime: '5h', cost: 650 },
  'penn-state': { name: 'Beaver Stadium', city: 'State College, PA', lat: 40.8122, lng: -77.8564, distance: 2400, airport: 'SCE', toStadium: '10 min from SCE', flight: '5h (1 stop)', totalTime: '8h', cost: 1100 },
  'purdue': { name: 'Ross-Ade Stadium', city: 'West Lafayette, IN', lat: 40.4419, lng: -86.9189, distance: 1900, airport: 'IND', toStadium: '1h from IND', flight: '4h', totalTime: '7.5h', cost: 950 },
  'rutgers': { name: 'SHI Stadium', city: 'Piscataway, NJ', lat: 40.5138, lng: -74.4653, distance: 2500, airport: 'EWR', toStadium: '30 min from EWR', flight: '5h', totalTime: '8h', cost: 1100 },
  'ucla': { name: 'Rose Bowl', city: 'Pasadena, CA', lat: 34.1614, lng: -118.1676, distance: 25, airport: null, toStadium: '35 min drive', flight: '-', totalTime: '35 min', cost: 20 },
  'usc': { name: 'LA Memorial Coliseum', city: 'Los Angeles, CA', lat: 34.0141, lng: -118.2879, distance: 30, airport: null, toStadium: '45 min drive', flight: '-', totalTime: '45 min', cost: 25 },
  'washington': { name: 'Husky Stadium', city: 'Seattle, WA', lat: 47.6505, lng: -122.3017, distance: 1140, airport: 'SEA', toStadium: '20 min from SEA', flight: '2.5h', totalTime: '5.5h', cost: 700 },
  'wisconsin': { name: 'Camp Randall Stadium', city: 'Madison, WI', lat: 43.0700, lng: -89.4128, distance: 1850, airport: 'MSN', toStadium: '15 min from MSN', flight: '4h (1 stop)', totalTime: '7h', cost: 950 },
  
  // NEUTRAL SITES
  'dallas': { name: 'Cotton Bowl', city: 'Dallas, TX', lat: 32.7782, lng: -96.7595, distance: 1440, airport: 'DFW', toStadium: '25 min from DFW', flight: '3h', totalTime: '6h', cost: 850 },
  'atlanta': { name: 'Mercedes-Benz Stadium', city: 'Atlanta, GA', lat: 33.7553, lng: -84.4006, distance: 2000, airport: 'ATL', toStadium: '15 min from ATL', flight: '4h', totalTime: '6.5h', cost: 950 },
  'nashville': { name: 'Nissan Stadium', city: 'Nashville, TN', lat: 36.1665, lng: -86.7713, distance: 1850, airport: 'BNA', toStadium: '10 min from BNA', flight: '4h', totalTime: '6.5h', cost: 950 },
  'jacksonville': { name: 'EverBank Stadium', city: 'Jacksonville, FL', lat: 30.3239, lng: -81.6373, distance: 2300, airport: 'JAX', toStadium: '15 min from JAX', flight: '5h (1 stop)', totalTime: '8h', cost: 1100 },
  'green-bay': { name: 'Lambeau Field', city: 'Green Bay, WI', lat: 44.5013, lng: -88.0622, distance: 1950, airport: 'GRB', toStadium: '10 min from GRB', flight: '4.5h (1 stop)', totalTime: '7.5h', cost: 1000 }
};

// Team info
const TEAMS = {
  // SEC
  'alabama': { name: 'Alabama', mascot: 'Crimson Tide', abbr: 'ALA', conference: 'SEC', color: '#9E1B32' },
  'arkansas': { name: 'Arkansas', mascot: 'Razorbacks', abbr: 'ARK', conference: 'SEC', color: '#9D2235' },
  'auburn': { name: 'Auburn', mascot: 'Tigers', abbr: 'AUB', conference: 'SEC', color: '#0C2340' },
  'florida': { name: 'Florida', mascot: 'Gators', abbr: 'FLA', conference: 'SEC', color: '#0021A5' },
  'georgia': { name: 'Georgia', mascot: 'Bulldogs', abbr: 'UGA', conference: 'SEC', color: '#BA0C2F' },
  'kentucky': { name: 'Kentucky', mascot: 'Wildcats', abbr: 'UK', conference: 'SEC', color: '#0033A0' },
  'lsu': { name: 'LSU', mascot: 'Tigers', abbr: 'LSU', conference: 'SEC', color: '#461D7C' },
  'mississippi-state': { name: 'Mississippi State', mascot: 'Bulldogs', abbr: 'MSU', conference: 'SEC', color: '#660000' },
  'missouri': { name: 'Missouri', mascot: 'Tigers', abbr: 'MIZ', conference: 'SEC', color: '#F1B82D' },
  'oklahoma': { name: 'Oklahoma', mascot: 'Sooners', abbr: 'OU', conference: 'SEC', color: '#841617' },
  'ole-miss': { name: 'Ole Miss', mascot: 'Rebels', abbr: 'MISS', conference: 'SEC', color: '#CE1126' },
  'south-carolina': { name: 'South Carolina', mascot: 'Gamecocks', abbr: 'SC', conference: 'SEC', color: '#73000A' },
  'tennessee': { name: 'Tennessee', mascot: 'Volunteers', abbr: 'TENN', conference: 'SEC', color: '#FF8200' },
  'texas': { name: 'Texas', mascot: 'Longhorns', abbr: 'TEX', conference: 'SEC', color: '#BF5700' },
  'texas-am': { name: 'Texas A&M', mascot: 'Aggies', abbr: 'TAMU', conference: 'SEC', color: '#500000' },
  'vanderbilt': { name: 'Vanderbilt', mascot: 'Commodores', abbr: 'VAN', conference: 'SEC', color: '#866D4B' },
  
  // Big Ten
  'illinois': { name: 'Illinois', mascot: 'Fighting Illini', abbr: 'ILL', conference: 'Big Ten', color: '#E84A27' },
  'indiana': { name: 'Indiana', mascot: 'Hoosiers', abbr: 'IND', conference: 'Big Ten', color: '#990000' },
  'iowa': { name: 'Iowa', mascot: 'Hawkeyes', abbr: 'IOWA', conference: 'Big Ten', color: '#FFCD00' },
  'maryland': { name: 'Maryland', mascot: 'Terrapins', abbr: 'MD', conference: 'Big Ten', color: '#E03A3E' },
  'michigan': { name: 'Michigan', mascot: 'Wolverines', abbr: 'MICH', conference: 'Big Ten', color: '#00274C' },
  'michigan-state': { name: 'Michigan State', mascot: 'Spartans', abbr: 'MSU', conference: 'Big Ten', color: '#18453B' },
  'minnesota': { name: 'Minnesota', mascot: 'Golden Gophers', abbr: 'MINN', conference: 'Big Ten', color: '#7A0019' },
  'nebraska': { name: 'Nebraska', mascot: 'Cornhuskers', abbr: 'NEB', conference: 'Big Ten', color: '#E41C38' },
  'northwestern': { name: 'Northwestern', mascot: 'Wildcats', abbr: 'NW', conference: 'Big Ten', color: '#4E2A84' },
  'ohio-state': { name: 'Ohio State', mascot: 'Buckeyes', abbr: 'OSU', conference: 'Big Ten', color: '#BB0000' },
  'oregon': { name: 'Oregon', mascot: 'Ducks', abbr: 'ORE', conference: 'Big Ten', color: '#154733' },
  'penn-state': { name: 'Penn State', mascot: 'Nittany Lions', abbr: 'PSU', conference: 'Big Ten', color: '#041E42' },
  'purdue': { name: 'Purdue', mascot: 'Boilermakers', abbr: 'PUR', conference: 'Big Ten', color: '#CEB888' },
  'rutgers': { name: 'Rutgers', mascot: 'Scarlet Knights', abbr: 'RUT', conference: 'Big Ten', color: '#CC0033' },
  'ucla': { name: 'UCLA', mascot: 'Bruins', abbr: 'UCLA', conference: 'Big Ten', color: '#2D68C4' },
  'usc': { name: 'USC', mascot: 'Trojans', abbr: 'USC', conference: 'Big Ten', color: '#990000' },
  'washington': { name: 'Washington', mascot: 'Huskies', abbr: 'WASH', conference: 'Big Ten', color: '#4B2E83' },
  'wisconsin': { name: 'Wisconsin', mascot: 'Badgers', abbr: 'WIS', conference: 'Big Ten', color: '#C5050C' }
};

// 2026 Schedules - Based on official conference announcements
const SCHEDULES = {
  'alabama': [
    { date: 'Sep 5', opponent: 'East Carolina', location: 'alabama', type: 'home' },
    { date: 'Sep 12', opponent: 'Kentucky', location: 'kentucky', type: 'away' },
    { date: 'Sep 19', opponent: 'Florida State', location: 'alabama', type: 'home' },
    { date: 'Sep 26', opponent: 'South Carolina', location: 'alabama', type: 'home' },
    { date: 'Oct 3', opponent: 'Mississippi State', location: 'mississippi-state', type: 'away' },
    { date: 'Oct 10', opponent: 'Georgia', location: 'alabama', type: 'home' },
    { date: 'Oct 17', opponent: 'Tennessee', location: 'tennessee', type: 'away' },
    { date: 'Oct 24', opponent: 'Texas A&M', location: 'alabama', type: 'home' },
    { date: 'Nov 7', opponent: 'LSU', location: 'lsu', type: 'away' },
    { date: 'Nov 14', opponent: 'Vanderbilt', location: 'vanderbilt', type: 'away' },
    { date: 'Nov 21', opponent: 'Chattanooga', location: 'alabama', type: 'home' },
    { date: 'Nov 28', opponent: 'Auburn', location: 'alabama', type: 'home' }
  ],
  'georgia': [
    { date: 'Sep 5', opponent: 'Tennessee State', location: 'georgia', type: 'home' },
    { date: 'Sep 12', opponent: 'Western Kentucky', location: 'georgia', type: 'home' },
    { date: 'Sep 19', opponent: 'Arkansas', location: 'arkansas', type: 'away' },
    { date: 'Sep 26', opponent: 'Oklahoma', location: 'georgia', type: 'home' },
    { date: 'Oct 3', opponent: 'Vanderbilt', location: 'georgia', type: 'home' },
    { date: 'Oct 10', opponent: 'Alabama', location: 'alabama', type: 'away' },
    { date: 'Oct 17', opponent: 'Auburn', location: 'georgia', type: 'home' },
    { date: 'Oct 31', opponent: 'Florida', location: 'jacksonville', type: 'neutral' },
    { date: 'Nov 7', opponent: 'Ole Miss', location: 'ole-miss', type: 'away' },
    { date: 'Nov 14', opponent: 'Missouri', location: 'georgia', type: 'home' },
    { date: 'Nov 21', opponent: 'South Carolina', location: 'south-carolina', type: 'away' },
    { date: 'Nov 28', opponent: 'Georgia Tech', location: 'georgia', type: 'home' }
  ],
  'ohio-state': [
    { date: 'Sep 5', opponent: 'Texas', location: 'ohio-state', type: 'home' },
    { date: 'Sep 12', opponent: 'Texas', location: 'texas', type: 'away' },
    { date: 'Sep 19', opponent: 'TBD', location: 'ohio-state', type: 'home' },
    { date: 'Sep 26', opponent: 'Indiana', location: 'indiana', type: 'away' },
    { date: 'Oct 10', opponent: 'Iowa', location: 'ohio-state', type: 'home' },
    { date: 'Oct 17', opponent: 'Nebraska', location: 'nebraska', type: 'away' },
    { date: 'Oct 24', opponent: 'Penn State', location: 'ohio-state', type: 'home' },
    { date: 'Oct 31', opponent: 'Oregon', location: 'oregon', type: 'away' },
    { date: 'Nov 7', opponent: 'Purdue', location: 'ohio-state', type: 'home' },
    { date: 'Nov 14', opponent: 'Northwestern', location: 'northwestern', type: 'away' },
    { date: 'Nov 21', opponent: 'Maryland', location: 'ohio-state', type: 'home' },
    { date: 'Nov 28', opponent: 'Michigan', location: 'michigan', type: 'away' }
  ],
  'michigan': [
    { date: 'Sep 5', opponent: 'TBD', location: 'michigan', type: 'home' },
    { date: 'Sep 12', opponent: 'Oklahoma', location: 'michigan', type: 'home' },
    { date: 'Sep 19', opponent: 'Illinois', location: 'illinois', type: 'away' },
    { date: 'Sep 26', opponent: 'Minnesota', location: 'michigan', type: 'home' },
    { date: 'Oct 10', opponent: 'Rutgers', location: 'rutgers', type: 'away' },
    { date: 'Oct 17', opponent: 'Northwestern', location: 'michigan', type: 'home' },
    { date: 'Oct 24', opponent: 'Michigan State', location: 'michigan-state', type: 'away' },
    { date: 'Oct 31', opponent: 'Wisconsin', location: 'michigan', type: 'home' },
    { date: 'Nov 7', opponent: 'Indiana', location: 'michigan', type: 'home' },
    { date: 'Nov 14', opponent: 'Washington', location: 'washington', type: 'away' },
    { date: 'Nov 21', opponent: 'Purdue', location: 'purdue', type: 'away' },
    { date: 'Nov 28', opponent: 'Ohio State', location: 'michigan', type: 'home' }
  ],
  'texas': [
    { date: 'Sep 5', opponent: 'Texas State', location: 'texas', type: 'home' },
    { date: 'Sep 12', opponent: 'Ohio State', location: 'texas', type: 'home' },
    { date: 'Sep 19', opponent: 'UTSA', location: 'texas', type: 'home' },
    { date: 'Sep 26', opponent: 'Tennessee', location: 'tennessee', type: 'away' },
    { date: 'Oct 10', opponent: 'Oklahoma', location: 'dallas', type: 'neutral' },
    { date: 'Oct 17', opponent: 'Florida', location: 'texas', type: 'home' },
    { date: 'Oct 24', opponent: 'Ole Miss', location: 'texas', type: 'home' },
    { date: 'Oct 31', opponent: 'Mississippi State', location: 'texas', type: 'home' },
    { date: 'Nov 7', opponent: 'Missouri', location: 'missouri', type: 'away' },
    { date: 'Nov 14', opponent: 'LSU', location: 'lsu', type: 'away' },
    { date: 'Nov 21', opponent: 'Arkansas', location: 'texas', type: 'home' },
    { date: 'Nov 27', opponent: 'Texas A&M', location: 'texas-am', type: 'away' }
  ],
  'lsu': [
    { date: 'Sep 5', opponent: 'Clemson', location: 'lsu', type: 'home' },
    { date: 'Sep 12', opponent: 'Louisiana Tech', location: 'lsu', type: 'home' },
    { date: 'Sep 19', opponent: 'Ole Miss', location: 'ole-miss', type: 'away' },
    { date: 'Sep 26', opponent: 'Texas A&M', location: 'lsu', type: 'home' },
    { date: 'Oct 3', opponent: 'McNeese State', location: 'lsu', type: 'home' },
    { date: 'Oct 10', opponent: 'Kentucky', location: 'kentucky', type: 'away' },
    { date: 'Oct 17', opponent: 'Mississippi State', location: 'lsu', type: 'home' },
    { date: 'Oct 24', opponent: 'Auburn', location: 'auburn', type: 'away' },
    { date: 'Nov 7', opponent: 'Alabama', location: 'lsu', type: 'home' },
    { date: 'Nov 14', opponent: 'Texas', location: 'lsu', type: 'home' },
    { date: 'Nov 21', opponent: 'Tennessee', location: 'tennessee', type: 'away' },
    { date: 'Nov 28', opponent: 'Arkansas', location: 'arkansas', type: 'away' }
  ],
  'ucla': [
    { date: 'Sep 5', opponent: 'California', location: 'california', type: 'away' },
    { date: 'Sep 12', opponent: 'San Diego State', location: 'ucla', type: 'home' },
    { date: 'Sep 19', opponent: 'Purdue', location: 'ucla', type: 'home' },
    { date: 'Sep 26', opponent: 'Maryland', location: 'maryland', type: 'away' },
    { date: 'Oct 10', opponent: 'Oregon', location: 'oregon', type: 'away' },
    { date: 'Oct 17', opponent: 'Wisconsin', location: 'ucla', type: 'home' },
    { date: 'Oct 24', opponent: 'Michigan State', location: 'ucla', type: 'home' },
    { date: 'Oct 31', opponent: 'Nevada', location: 'ucla', type: 'home' },
    { date: 'Nov 7', opponent: 'Minnesota', location: 'minnesota', type: 'away' },
    { date: 'Nov 14', opponent: 'Illinois', location: 'ucla', type: 'home' },
    { date: 'Nov 21', opponent: 'USC', location: 'usc', type: 'away' }
  ],
  'usc': [
    { date: 'Sep 5', opponent: 'TBD', location: 'usc', type: 'home' },
    { date: 'Sep 12', opponent: 'Fresno State', location: 'usc', type: 'home' },
    { date: 'Sep 19', opponent: 'Wisconsin', location: 'wisconsin', type: 'away' },
    { date: 'Sep 26', opponent: 'Rutgers', location: 'usc', type: 'home' },
    { date: 'Oct 10', opponent: 'Penn State', location: 'penn-state', type: 'away' },
    { date: 'Oct 17', opponent: 'Minnesota', location: 'usc', type: 'home' },
    { date: 'Oct 24', opponent: 'Nebraska', location: 'usc', type: 'home' },
    { date: 'Oct 31', opponent: 'Washington', location: 'washington', type: 'away' },
    { date: 'Nov 7', opponent: 'Oregon', location: 'usc', type: 'home' },
    { date: 'Nov 14', opponent: 'Purdue', location: 'purdue', type: 'away' },
    { date: 'Nov 21', opponent: 'UCLA', location: 'usc', type: 'home' }
  ],
  'oregon': [
    { date: 'Sep 5', opponent: 'TBD', location: 'oregon', type: 'home' },
    { date: 'Sep 12', opponent: 'Oklahoma State', location: 'oregon', type: 'home' },
    { date: 'Sep 19', opponent: 'Nebraska', location: 'oregon', type: 'home' },
    { date: 'Sep 26', opponent: 'Illinois', location: 'oregon', type: 'home' },
    { date: 'Oct 10', opponent: 'UCLA', location: 'oregon', type: 'home' },
    { date: 'Oct 17', opponent: 'Purdue', location: 'purdue', type: 'away' },
    { date: 'Oct 24', opponent: 'Iowa', location: 'iowa', type: 'away' },
    { date: 'Oct 31', opponent: 'Ohio State', location: 'oregon', type: 'home' },
    { date: 'Nov 7', opponent: 'USC', location: 'usc', type: 'away' },
    { date: 'Nov 14', opponent: 'Michigan State', location: 'michigan-state', type: 'away' },
    { date: 'Nov 21', opponent: 'Washington', location: 'oregon', type: 'home' }
  ],
  'washington': [
    { date: 'Sep 5', opponent: 'Washington State', location: 'washington', type: 'home' },
    { date: 'Sep 12', opponent: 'TBD', location: 'washington', type: 'home' },
    { date: 'Sep 19', opponent: 'Iowa', location: 'washington', type: 'home' },
    { date: 'Sep 26', opponent: 'Northwestern', location: 'northwestern', type: 'away' },
    { date: 'Oct 10', opponent: 'Indiana', location: 'indiana', type: 'away' },
    { date: 'Oct 17', opponent: 'Illinois', location: 'washington', type: 'home' },
    { date: 'Oct 24', opponent: 'Maryland', location: 'washington', type: 'home' },
    { date: 'Oct 31', opponent: 'USC', location: 'washington', type: 'home' },
    { date: 'Nov 7', opponent: 'Wisconsin', location: 'wisconsin', type: 'away' },
    { date: 'Nov 14', opponent: 'Michigan', location: 'washington', type: 'home' },
    { date: 'Nov 21', opponent: 'Oregon', location: 'oregon', type: 'away' }
  ],
  'tennessee': [
    { date: 'Sep 5', opponent: 'Furman', location: 'tennessee', type: 'home' },
    { date: 'Sep 12', opponent: 'Georgia Tech', location: 'tennessee', type: 'away' },
    { date: 'Sep 19', opponent: 'Kennesaw State', location: 'tennessee', type: 'home' },
    { date: 'Sep 26', opponent: 'Texas', location: 'tennessee', type: 'home' },
    { date: 'Oct 3', opponent: 'Auburn', location: 'tennessee', type: 'home' },
    { date: 'Oct 10', opponent: 'Arkansas', location: 'arkansas', type: 'away' },
    { date: 'Oct 17', opponent: 'Alabama', location: 'tennessee', type: 'home' },
    { date: 'Oct 24', opponent: 'South Carolina', location: 'south-carolina', type: 'away' },
    { date: 'Nov 7', opponent: 'Kentucky', location: 'tennessee', type: 'home' },
    { date: 'Nov 14', opponent: 'Texas A&M', location: 'texas-am', type: 'away' },
    { date: 'Nov 21', opponent: 'LSU', location: 'tennessee', type: 'home' },
    { date: 'Nov 28', opponent: 'Vanderbilt', location: 'vanderbilt', type: 'away' }
  ],
  'florida': [
    { date: 'Sep 5', opponent: 'Florida Atlantic', location: 'florida', type: 'home' },
    { date: 'Sep 12', opponent: 'Campbell', location: 'florida', type: 'home' },
    { date: 'Sep 19', opponent: 'Auburn', location: 'auburn', type: 'away' },
    { date: 'Sep 26', opponent: 'Ole Miss', location: 'florida', type: 'home' },
    { date: 'Oct 3', opponent: 'Missouri', location: 'missouri', type: 'away' },
    { date: 'Oct 10', opponent: 'South Carolina', location: 'florida', type: 'home' },
    { date: 'Oct 17', opponent: 'Texas', location: 'texas', type: 'away' },
    { date: 'Oct 31', opponent: 'Georgia', location: 'jacksonville', type: 'neutral' },
    { date: 'Nov 7', opponent: 'Oklahoma', location: 'florida', type: 'home' },
    { date: 'Nov 14', opponent: 'Kentucky', location: 'kentucky', type: 'away' },
    { date: 'Nov 21', opponent: 'Vanderbilt', location: 'florida', type: 'home' },
    { date: 'Nov 28', opponent: 'Florida State', location: 'florida', type: 'away' }
  ],
  'oklahoma': [
    { date: 'Sep 5', opponent: 'UTEP', location: 'oklahoma', type: 'home' },
    { date: 'Sep 12', opponent: 'Michigan', location: 'michigan', type: 'away' },
    { date: 'Sep 19', opponent: 'New Mexico', location: 'oklahoma', type: 'home' },
    { date: 'Sep 26', opponent: 'Georgia', location: 'georgia', type: 'away' },
    { date: 'Oct 10', opponent: 'Texas', location: 'dallas', type: 'neutral' },
    { date: 'Oct 17', opponent: 'Kentucky', location: 'oklahoma', type: 'home' },
    { date: 'Oct 24', opponent: 'Mississippi State', location: 'mississippi-state', type: 'away' },
    { date: 'Oct 31', opponent: 'South Carolina', location: 'oklahoma', type: 'home' },
    { date: 'Nov 7', opponent: 'Florida', location: 'florida', type: 'away' },
    { date: 'Nov 14', opponent: 'Ole Miss', location: 'oklahoma', type: 'home' },
    { date: 'Nov 21', opponent: 'Texas A&M', location: 'oklahoma', type: 'home' },
    { date: 'Nov 28', opponent: 'Missouri', location: 'missouri', type: 'away' }
  ],
  'auburn': [
    { date: 'Sep 5', opponent: 'Baylor', location: 'atlanta', type: 'neutral' },
    { date: 'Sep 12', opponent: 'Southern Miss', location: 'auburn', type: 'home' },
    { date: 'Sep 19', opponent: 'Florida', location: 'auburn', type: 'home' },
    { date: 'Sep 26', opponent: 'Vanderbilt', location: 'auburn', type: 'home' },
    { date: 'Oct 3', opponent: 'Tennessee', location: 'tennessee', type: 'away' },
    { date: 'Oct 17', opponent: 'Georgia', location: 'georgia', type: 'away' },
    { date: 'Oct 24', opponent: 'LSU', location: 'auburn', type: 'home' },
    { date: 'Oct 31', opponent: 'Ole Miss', location: 'ole-miss', type: 'away' },
    { date: 'Nov 7', opponent: 'Arkansas', location: 'auburn', type: 'home' },
    { date: 'Nov 14', opponent: 'Mississippi State', location: 'mississippi-state', type: 'away' },
    { date: 'Nov 21', opponent: 'Samford', location: 'auburn', type: 'home' },
    { date: 'Nov 28', opponent: 'Alabama', location: 'alabama', type: 'away' }
  ],
  'texas-am': [
    { date: 'Sep 5', opponent: 'Missouri State', location: 'texas-am', type: 'home' },
    { date: 'Sep 12', opponent: 'Arizona State', location: 'texas-am', type: 'home' },
    { date: 'Sep 19', opponent: 'Kentucky', location: 'texas-am', type: 'home' },
    { date: 'Sep 26', opponent: 'LSU', location: 'lsu', type: 'away' },
    { date: 'Oct 3', opponent: 'Arkansas', location: 'texas-am', type: 'home' },
    { date: 'Oct 10', opponent: 'Missouri', location: 'missouri', type: 'away' },
    { date: 'Oct 17', opponent: 'Citadel', location: 'texas-am', type: 'home' },
    { date: 'Oct 24', opponent: 'Alabama', location: 'alabama', type: 'away' },
    { date: 'Nov 7', opponent: 'South Carolina', location: 'south-carolina', type: 'away' },
    { date: 'Nov 14', opponent: 'Tennessee', location: 'texas-am', type: 'home' },
    { date: 'Nov 21', opponent: 'Oklahoma', location: 'oklahoma', type: 'away' },
    { date: 'Nov 27', opponent: 'Texas', location: 'texas-am', type: 'home' }
  ],
  'penn-state': [
    { date: 'Sep 5', opponent: 'Marshall', location: 'penn-state', type: 'home' },
    { date: 'Sep 12', opponent: 'TBD', location: 'penn-state', type: 'home' },
    { date: 'Sep 19', opponent: 'Rutgers', location: 'rutgers', type: 'away' },
    { date: 'Sep 26', opponent: 'Iowa', location: 'penn-state', type: 'home' },
    { date: 'Oct 10', opponent: 'USC', location: 'penn-state', type: 'home' },
    { date: 'Oct 17', opponent: 'Indiana', location: 'indiana', type: 'away' },
    { date: 'Oct 24', opponent: 'Ohio State', location: 'ohio-state', type: 'away' },
    { date: 'Oct 31', opponent: 'Illinois', location: 'penn-state', type: 'home' },
    { date: 'Nov 7', opponent: 'Minnesota', location: 'minnesota', type: 'away' },
    { date: 'Nov 14', opponent: 'Nebraska', location: 'penn-state', type: 'home' },
    { date: 'Nov 21', opponent: 'Michigan State', location: 'penn-state', type: 'home' }
  ],
  'wisconsin': [
    { date: 'Sep 5', opponent: 'Notre Dame', location: 'green-bay', type: 'neutral' },
    { date: 'Sep 12', opponent: 'TBD', location: 'wisconsin', type: 'home' },
    { date: 'Sep 19', opponent: 'USC', location: 'wisconsin', type: 'home' },
    { date: 'Sep 26', opponent: 'Purdue', location: 'purdue', type: 'away' },
    { date: 'Oct 10', opponent: 'Nebraska', location: 'wisconsin', type: 'home' },
    { date: 'Oct 17', opponent: 'UCLA', location: 'ucla', type: 'away' },
    { date: 'Oct 24', opponent: 'Rutgers', location: 'wisconsin', type: 'home' },
    { date: 'Oct 31', opponent: 'Michigan', location: 'michigan', type: 'away' },
    { date: 'Nov 7', opponent: 'Washington', location: 'wisconsin', type: 'home' },
    { date: 'Nov 14', opponent: 'Iowa', location: 'iowa', type: 'away' },
    { date: 'Nov 21', opponent: 'Minnesota', location: 'wisconsin', type: 'home' }
  ],
  'minnesota': [
    { date: 'Sep 5', opponent: 'TBD', location: 'minnesota', type: 'home' },
    { date: 'Sep 12', opponent: 'Mississippi State', location: 'minnesota', type: 'home' },
    { date: 'Sep 19', opponent: 'Purdue', location: 'minnesota', type: 'home' },
    { date: 'Sep 26', opponent: 'Michigan', location: 'michigan', type: 'away' },
    { date: 'Oct 10', opponent: 'Maryland', location: 'maryland', type: 'away' },
    { date: 'Oct 17', opponent: 'USC', location: 'usc', type: 'away' },
    { date: 'Oct 24', opponent: 'Northwestern', location: 'minnesota', type: 'home' },
    { date: 'Oct 31', opponent: 'Indiana', location: 'indiana', type: 'away' },
    { date: 'Nov 7', opponent: 'UCLA', location: 'minnesota', type: 'home' },
    { date: 'Nov 14', opponent: 'Penn State', location: 'minnesota', type: 'home' },
    { date: 'Nov 21', opponent: 'Wisconsin', location: 'wisconsin', type: 'away' }
  ],
  'iowa': [
    { date: 'Sep 5', opponent: 'Iowa State', location: 'iowa', type: 'home' },
    { date: 'Sep 12', opponent: 'TBD', location: 'iowa', type: 'home' },
    { date: 'Sep 19', opponent: 'Washington', location: 'washington', type: 'away' },
    { date: 'Sep 26', opponent: 'Penn State', location: 'penn-state', type: 'away' },
    { date: 'Oct 10', opponent: 'Ohio State', location: 'ohio-state', type: 'away' },
    { date: 'Oct 17', opponent: 'Rutgers', location: 'iowa', type: 'home' },
    { date: 'Oct 24', opponent: 'Oregon', location: 'iowa', type: 'home' },
    { date: 'Oct 31', opponent: 'Nebraska', location: 'nebraska', type: 'away' },
    { date: 'Nov 7', opponent: 'Illinois', location: 'illinois', type: 'away' },
    { date: 'Nov 14', opponent: 'Wisconsin', location: 'iowa', type: 'home' },
    { date: 'Nov 21', opponent: 'Northwestern', location: 'iowa', type: 'home' }
  ],
  'nebraska': [
    { date: 'Sep 5', opponent: 'Ohio', location: 'nebraska', type: 'home' },
    { date: 'Sep 12', opponent: 'TBD', location: 'nebraska', type: 'home' },
    { date: 'Sep 19', opponent: 'Oregon', location: 'oregon', type: 'away' },
    { date: 'Sep 26', opponent: 'Maryland', location: 'nebraska', type: 'home' },
    { date: 'Oct 10', opponent: 'Wisconsin', location: 'wisconsin', type: 'away' },
    { date: 'Oct 17', opponent: 'Ohio State', location: 'nebraska', type: 'home' },
    { date: 'Oct 24', opponent: 'USC', location: 'usc', type: 'away' },
    { date: 'Oct 31', opponent: 'Iowa', location: 'nebraska', type: 'home' },
    { date: 'Nov 7', opponent: 'Purdue', location: 'purdue', type: 'away' },
    { date: 'Nov 14', opponent: 'Penn State', location: 'penn-state', type: 'away' },
    { date: 'Nov 21', opponent: 'Indiana', location: 'nebraska', type: 'home' }
  ],
  'illinois': [
    { date: 'Sep 5', opponent: 'Duke', location: 'illinois', type: 'home' },
    { date: 'Sep 12', opponent: 'TBD', location: 'illinois', type: 'home' },
    { date: 'Sep 19', opponent: 'Michigan', location: 'illinois', type: 'home' },
    { date: 'Sep 26', opponent: 'Oregon', location: 'oregon', type: 'away' },
    { date: 'Oct 10', opponent: 'Purdue', location: 'purdue', type: 'away' },
    { date: 'Oct 17', opponent: 'Washington', location: 'washington', type: 'away' },
    { date: 'Oct 24', opponent: 'Indiana', location: 'illinois', type: 'home' },
    { date: 'Oct 31', opponent: 'Penn State', location: 'penn-state', type: 'away' },
    { date: 'Nov 7', opponent: 'Iowa', location: 'illinois', type: 'home' },
    { date: 'Nov 14', opponent: 'UCLA', location: 'ucla', type: 'away' },
    { date: 'Nov 21', opponent: 'Northwestern', location: 'northwestern', type: 'away' }
  ],
  'indiana': [
    { date: 'Sep 5', opponent: 'North Texas', location: 'indiana', type: 'home' },
    { date: 'Sep 12', opponent: 'TBD', location: 'indiana', type: 'home' },
    { date: 'Sep 19', opponent: 'Northwestern', location: 'indiana', type: 'home' },
    { date: 'Sep 26', opponent: 'Ohio State', location: 'indiana', type: 'home' },
    { date: 'Oct 10', opponent: 'Washington', location: 'indiana', type: 'home' },
    { date: 'Oct 17', opponent: 'Penn State', location: 'penn-state', type: 'away' },
    { date: 'Oct 24', opponent: 'Illinois', location: 'illinois', type: 'away' },
    { date: 'Oct 31', opponent: 'Minnesota', location: 'indiana', type: 'home' },
    { date: 'Nov 7', opponent: 'Michigan', location: 'michigan', type: 'away' },
    { date: 'Nov 14', opponent: 'Rutgers', location: 'indiana', type: 'home' },
    { date: 'Nov 21', opponent: 'Nebraska', location: 'nebraska', type: 'away' }
  ],
  'maryland': [
    { date: 'Sep 5', opponent: 'TBD', location: 'maryland', type: 'home' },
    { date: 'Sep 12', opponent: 'Virginia Tech', location: 'maryland', type: 'home' },
    { date: 'Sep 19', opponent: 'Northwestern', location: 'maryland', type: 'home' },
    { date: 'Sep 26', opponent: 'UCLA', location: 'maryland', type: 'home' },
    { date: 'Oct 10', opponent: 'Minnesota', location: 'maryland', type: 'home' },
    { date: 'Oct 17', opponent: 'Rutgers', location: 'rutgers', type: 'away' },
    { date: 'Oct 24', opponent: 'Washington', location: 'washington', type: 'away' },
    { date: 'Oct 31', opponent: 'Michigan State', location: 'maryland', type: 'home' },
    { date: 'Nov 7', opponent: 'Nebraska', location: 'nebraska', type: 'away' },
    { date: 'Nov 14', opponent: 'Ohio State', location: 'ohio-state', type: 'away' },
    { date: 'Nov 21', opponent: 'Purdue', location: 'maryland', type: 'home' }
  ],
  'michigan-state': [
    { date: 'Sep 5', opponent: 'Notre Dame', location: 'michigan-state', type: 'away' },
    { date: 'Sep 12', opponent: 'TBD', location: 'michigan-state', type: 'home' },
    { date: 'Sep 19', opponent: 'Purdue', location: 'michigan-state', type: 'home' },
    { date: 'Sep 26', opponent: 'Rutgers', location: 'rutgers', type: 'away' },
    { date: 'Oct 10', opponent: 'Northwestern', location: 'michigan-state', type: 'home' },
    { date: 'Oct 17', opponent: 'Iowa', location: 'iowa', type: 'away' },
    { date: 'Oct 24', opponent: 'Michigan', location: 'michigan-state', type: 'home' },
    { date: 'Oct 31', opponent: 'Maryland', location: 'maryland', type: 'away' },
    { date: 'Nov 7', opponent: 'Indiana', location: 'indiana', type: 'away' },
    { date: 'Nov 14', opponent: 'Oregon', location: 'michigan-state', type: 'home' },
    { date: 'Nov 21', opponent: 'Penn State', location: 'penn-state', type: 'away' }
  ],
  'northwestern': [
    { date: 'Sep 5', opponent: 'Colorado', location: 'northwestern', type: 'home' },
    { date: 'Sep 12', opponent: 'TBD', location: 'northwestern', type: 'home' },
    { date: 'Sep 19', opponent: 'Indiana', location: 'indiana', type: 'away' },
    { date: 'Sep 26', opponent: 'Washington', location: 'northwestern', type: 'home' },
    { date: 'Oct 10', opponent: 'Michigan State', location: 'michigan-state', type: 'away' },
    { date: 'Oct 17', opponent: 'Michigan', location: 'michigan', type: 'away' },
    { date: 'Oct 24', opponent: 'Minnesota', location: 'minnesota', type: 'away' },
    { date: 'Oct 31', opponent: 'Purdue', location: 'northwestern', type: 'home' },
    { date: 'Nov 7', opponent: 'Rutgers', location: 'northwestern', type: 'home' },
    { date: 'Nov 14', opponent: 'Ohio State', location: 'northwestern', type: 'home' },
    { date: 'Nov 21', opponent: 'Illinois', location: 'northwestern', type: 'home' }
  ],
  'purdue': [
    { date: 'Sep 5', opponent: 'Notre Dame', location: 'purdue', type: 'home' },
    { date: 'Sep 12', opponent: 'TBD', location: 'purdue', type: 'home' },
    { date: 'Sep 19', opponent: 'Michigan State', location: 'michigan-state', type: 'away' },
    { date: 'Sep 26', opponent: 'Wisconsin', location: 'purdue', type: 'home' },
    { date: 'Oct 10', opponent: 'Illinois', location: 'purdue', type: 'home' },
    { date: 'Oct 17', opponent: 'Oregon', location: 'purdue', type: 'home' },
    { date: 'Oct 24', opponent: 'Minnesota', location: 'minnesota', type: 'away' },
    { date: 'Oct 31', opponent: 'Northwestern', location: 'northwestern', type: 'away' },
    { date: 'Nov 7', opponent: 'Nebraska', location: 'purdue', type: 'home' },
    { date: 'Nov 14', opponent: 'USC', location: 'purdue', type: 'home' },
    { date: 'Nov 21', opponent: 'Michigan', location: 'purdue', type: 'home' }
  ],
  'rutgers': [
    { date: 'Sep 5', opponent: 'Boston College', location: 'rutgers', type: 'away' },
    { date: 'Sep 12', opponent: 'TBD', location: 'rutgers', type: 'home' },
    { date: 'Sep 19', opponent: 'Penn State', location: 'rutgers', type: 'home' },
    { date: 'Sep 26', opponent: 'Michigan State', location: 'rutgers', type: 'home' },
    { date: 'Oct 10', opponent: 'Michigan', location: 'rutgers', type: 'home' },
    { date: 'Oct 17', opponent: 'Maryland', location: 'rutgers', type: 'home' },
    { date: 'Oct 24', opponent: 'Wisconsin', location: 'wisconsin', type: 'away' },
    { date: 'Oct 31', opponent: 'Iowa', location: 'iowa', type: 'away' },
    { date: 'Nov 7', opponent: 'Northwestern', location: 'northwestern', type: 'away' },
    { date: 'Nov 14', opponent: 'Indiana', location: 'indiana', type: 'away' },
    { date: 'Nov 21', opponent: 'USC', location: 'rutgers', type: 'home' }
  ],
  'arkansas': [
    { date: 'Sep 5', opponent: 'North Alabama', location: 'arkansas', type: 'home' },
    { date: 'Sep 12', opponent: 'Utah', location: 'arkansas', type: 'away' },
    { date: 'Sep 19', opponent: 'Georgia', location: 'arkansas', type: 'home' },
    { date: 'Sep 26', opponent: 'Tulsa', location: 'arkansas', type: 'home' },
    { date: 'Oct 3', opponent: 'Texas A&M', location: 'texas-am', type: 'away' },
    { date: 'Oct 10', opponent: 'Tennessee', location: 'arkansas', type: 'home' },
    { date: 'Oct 17', opponent: 'Vanderbilt', location: 'vanderbilt', type: 'away' },
    { date: 'Oct 31', opponent: 'Missouri', location: 'arkansas', type: 'home' },
    { date: 'Nov 7', opponent: 'Auburn', location: 'auburn', type: 'away' },
    { date: 'Nov 14', opponent: 'South Carolina', location: 'arkansas', type: 'home' },
    { date: 'Nov 21', opponent: 'Texas', location: 'texas', type: 'away' },
    { date: 'Nov 28', opponent: 'LSU', location: 'arkansas', type: 'home' }
  ],
  'kentucky': [
    { date: 'Sep 5', opponent: 'Youngstown State', location: 'kentucky', type: 'home' },
    { date: 'Sep 12', opponent: 'Alabama', location: 'kentucky', type: 'home' },
    { date: 'Sep 19', opponent: 'Texas A&M', location: 'texas-am', type: 'away' },
    { date: 'Sep 26', opponent: 'South Alabama', location: 'kentucky', type: 'home' },
    { date: 'Oct 3', opponent: 'South Carolina', location: 'south-carolina', type: 'away' },
    { date: 'Oct 10', opponent: 'LSU', location: 'kentucky', type: 'home' },
    { date: 'Oct 17', opponent: 'Oklahoma', location: 'oklahoma', type: 'away' },
    { date: 'Oct 24', opponent: 'Vanderbilt', location: 'kentucky', type: 'home' },
    { date: 'Nov 7', opponent: 'Tennessee', location: 'tennessee', type: 'away' },
    { date: 'Nov 14', opponent: 'Florida', location: 'kentucky', type: 'home' },
    { date: 'Nov 21', opponent: 'Missouri', location: 'missouri', type: 'away' },
    { date: 'Nov 28', opponent: 'Louisville', location: 'kentucky', type: 'home' }
  ],
  'mississippi-state': [
    { date: 'Sep 5', opponent: 'ULM', location: 'mississippi-state', type: 'home' },
    { date: 'Sep 12', opponent: 'Minnesota', location: 'minnesota', type: 'away' },
    { date: 'Sep 19', opponent: 'South Carolina', location: 'south-carolina', type: 'away' },
    { date: 'Sep 26', opponent: 'Missouri', location: 'mississippi-state', type: 'home' },
    { date: 'Oct 3', opponent: 'Alabama', location: 'mississippi-state', type: 'home' },
    { date: 'Oct 17', opponent: 'LSU', location: 'lsu', type: 'away' },
    { date: 'Oct 24', opponent: 'Oklahoma', location: 'mississippi-state', type: 'home' },
    { date: 'Oct 31', opponent: 'Texas', location: 'texas', type: 'away' },
    { date: 'Nov 7', opponent: 'Vanderbilt', location: 'mississippi-state', type: 'home' },
    { date: 'Nov 14', opponent: 'Auburn', location: 'mississippi-state', type: 'home' },
    { date: 'Nov 21', opponent: 'Tennessee Tech', location: 'mississippi-state', type: 'home' },
    { date: 'Nov 28', opponent: 'Ole Miss', location: 'ole-miss', type: 'away' }
  ],
  'missouri': [
    { date: 'Sep 5', opponent: 'Arkansas-Pine Bluff', location: 'missouri', type: 'home' },
    { date: 'Sep 12', opponent: 'Kansas', location: 'missouri', type: 'away' },
    { date: 'Sep 19', opponent: 'Troy', location: 'missouri', type: 'home' },
    { date: 'Sep 26', opponent: 'Mississippi State', location: 'mississippi-state', type: 'away' },
    { date: 'Oct 3', opponent: 'Florida', location: 'missouri', type: 'home' },
    { date: 'Oct 10', opponent: 'Texas A&M', location: 'missouri', type: 'home' },
    { date: 'Oct 17', opponent: 'Ole Miss', location: 'ole-miss', type: 'away' },
    { date: 'Oct 31', opponent: 'Arkansas', location: 'arkansas', type: 'away' },
    { date: 'Nov 7', opponent: 'Texas', location: 'missouri', type: 'home' },
    { date: 'Nov 14', opponent: 'Georgia', location: 'georgia', type: 'away' },
    { date: 'Nov 21', opponent: 'Kentucky', location: 'missouri', type: 'home' },
    { date: 'Nov 28', opponent: 'Oklahoma', location: 'missouri', type: 'home' }
  ],
  'ole-miss': [
    { date: 'Sep 5', opponent: 'Louisville', location: 'nashville', type: 'neutral' },
    { date: 'Sep 12', opponent: 'Charlotte', location: 'ole-miss', type: 'home' },
    { date: 'Sep 19', opponent: 'LSU', location: 'ole-miss', type: 'home' },
    { date: 'Sep 26', opponent: 'Florida', location: 'florida', type: 'away' },
    { date: 'Oct 10', opponent: 'Vanderbilt', location: 'ole-miss', type: 'home' },
    { date: 'Oct 17', opponent: 'Missouri', location: 'ole-miss', type: 'home' },
    { date: 'Oct 24', opponent: 'Texas', location: 'texas', type: 'away' },
    { date: 'Oct 31', opponent: 'Auburn', location: 'ole-miss', type: 'home' },
    { date: 'Nov 7', opponent: 'Georgia', location: 'ole-miss', type: 'home' },
    { date: 'Nov 14', opponent: 'Oklahoma', location: 'oklahoma', type: 'away' },
    { date: 'Nov 21', opponent: 'Wofford', location: 'ole-miss', type: 'home' },
    { date: 'Nov 28', opponent: 'Mississippi State', location: 'ole-miss', type: 'home' }
  ],
  'south-carolina': [
    { date: 'Sep 5', opponent: 'Kent State', location: 'south-carolina', type: 'home' },
    { date: 'Sep 12', opponent: 'Towson', location: 'south-carolina', type: 'home' },
    { date: 'Sep 19', opponent: 'Mississippi State', location: 'south-carolina', type: 'home' },
    { date: 'Sep 26', opponent: 'Alabama', location: 'alabama', type: 'away' },
    { date: 'Oct 3', opponent: 'Kentucky', location: 'south-carolina', type: 'home' },
    { date: 'Oct 10', opponent: 'Florida', location: 'florida', type: 'away' },
    { date: 'Oct 24', opponent: 'Tennessee', location: 'south-carolina', type: 'home' },
    { date: 'Oct 31', opponent: 'Oklahoma', location: 'oklahoma', type: 'away' },
    { date: 'Nov 7', opponent: 'Texas A&M', location: 'south-carolina', type: 'home' },
    { date: 'Nov 14', opponent: 'Arkansas', location: 'arkansas', type: 'away' },
    { date: 'Nov 21', opponent: 'Georgia', location: 'south-carolina', type: 'home' },
    { date: 'Nov 28', opponent: 'Clemson', location: 'south-carolina', type: 'away' }
  ],
  'vanderbilt': [
    { date: 'Sep 5', opponent: 'Austin Peay', location: 'vanderbilt', type: 'home' },
    { date: 'Sep 12', opponent: 'Delaware', location: 'vanderbilt', type: 'home' },
    { date: 'Sep 19', opponent: 'NC State', location: 'vanderbilt', type: 'home' },
    { date: 'Sep 26', opponent: 'Auburn', location: 'auburn', type: 'away' },
    { date: 'Oct 3', opponent: 'Georgia', location: 'georgia', type: 'away' },
    { date: 'Oct 10', opponent: 'Ole Miss', location: 'vanderbilt', type: 'away' },
    { date: 'Oct 17', opponent: 'Arkansas', location: 'vanderbilt', type: 'home' },
    { date: 'Oct 24', opponent: 'Kentucky', location: 'kentucky', type: 'away' },
    { date: 'Nov 7', opponent: 'Mississippi State', location: 'mississippi-state', type: 'away' },
    { date: 'Nov 14', opponent: 'Alabama', location: 'vanderbilt', type: 'home' },
    { date: 'Nov 21', opponent: 'Florida', location: 'florida', type: 'away' },
    { date: 'Nov 28', opponent: 'Tennessee', location: 'vanderbilt', type: 'home' }
  ]
};

// Add California as a non-conference destination for Berkeley
STADIUMS['california'] = { name: 'California Memorial Stadium', city: 'Berkeley, CA', lat: 37.8708, lng: -122.2506, distance: 340, airport: 'OAK', toStadium: '20 min from OAK', flight: '1h 15m', totalTime: '4.5h', cost: 450 };
